#The below assignment question is generated by AI.
#Ass 1

name = input("what's your name? ")
print("Welcome, "+ name)

favorite = input("what's is the name of your favourite Madrasa? ")
print(favorite)

print("Welcome, ",name, "Ma Shaa' Allah, can you tell me about ", favorite,"?")


